spring:
  main:
    web-application-type: none
  datasource:
    driverClassName : org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

network:
  sockets:
    - "127.0.0.1:8082"
    - "192.168.0.1:80"

service:
  restfuls:
    - "http://127.0.0.1:8080/rest/health"
    - "https://blog.elliot.tw"